language: node_js
node_js:
  - 5.1

before_install:
  - npm install -g gulp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=99.0

script: gulp test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email: false
