language: ruby
rvm:
  - 2.2

before_script:
 - chmod +x ./script/cibuild


install: npm install
script: gulp test

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler

notifications:
  email: false
